import React from 'react'
import './Carousel.css'
import { Swiper, SwiperSlide } from "swiper/react";
import video from "../assest/video-8.mp4";
import { useEffect, useState } from "react";

function Carousel() {
  const [activeSlide, setActiveSlide] = useState(0);
  const totalSlides = 4; // Total number of slides
  useEffect(() => {
    const interval = setInterval(() => {
      // Only advance to the next slide if it's not the currently active slide
      if (activeSlide !== totalSlides - 1) {
        setActiveSlide((prevSlide) => prevSlide + 1);
      } else {
        setActiveSlide(0); // Go back to the first slide
      }
    }, 2000);

    return () => {
      clearInterval(interval);
    };
  }, [activeSlide, totalSlides]);

  const handleClick = (index) => {
    setActiveSlide(index);
  };

  return (
    <>
      {/* <div className='mainCarousel'>
        <div id="carouselExampleCaptions" className="carousel slide m-5" data-bs-ride="carousel">
          <div className="carousel-indyicators indicater">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" className="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>

          </div>
          <div className="carousel-inner">
            <div className="carousel-item active carousel-img">
              <h1 style={{ fontFamily: 'serif' }}>Amplify your team’s productivity by integrating with your favorite tools, or customize Confluence with 2,500+ Marketplace apps like Slack or Teams. </h1>
            </div>
            <div className="carousel-item carousel-img">

              <h1 style={{ fontFamily: 'serif' }}>Market share is the percent of total sales in an industry generated by a particular company. Market share is calculated by taking the company's sales over the period and dividing it by the total sales of the industry over the same period. </h1>


            </div>
            <div className="carousel-item carousel-img">

              <h1 style={{ fontFamily: 'serif' }}>Boost your Immunity with Our Saffron Tea</h1>


            </div>
            <div className="carousel-item carousel-img">

              <h1 style={{ fontFamily: 'serif' }}> Start your Day with our Special Herbal Tea </h1>

            </div>
          </div>
          <button className="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
            <span className="carousel-control-prev-icon" aria-hidden="true"></span>

            <span className="visually-hidden"></span>
          </button>
          <button className="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
            <span className="carousel-control-next-icon" aria-hidden="true"></span>
            <span className="visually-hidden"></span>
          </button>
        </div>

      </div> */}
      <video autoPlay loop muted className="video">
        <source src={video} type="video/mp4" />
      </video>
      <section className="container">
        <div
          id="carouselExampleCaptions"
          class="carousel slide"
          data-bs-ride="carousel"
          className="content"
          data-bs-interval="2000"
        >
          <div class="carousel-indicators">
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="0"
              className={activeSlide === 0 ? "active" : ""}
              aria-current={activeSlide === 0 ? "true" : "false"}
              class="active"
              // aria-current="true"
              aria-label="Slide 1"
              style={{ width: "25%", marginLeft: "-380px", marginTop: "-90px" }}
              onClick={() => handleClick(0)}
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="1"
              className={activeSlide === 1 ? "active" : ""}
              aria-current={activeSlide === 1 ? "true" : "false"}
              aria-label="Slide 2"
              data-interval="1000"
              style={{ width: "25%", marginTop: "-90px" }}
              onClick={() => handleClick(1)}
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="2"
              className={activeSlide === 2 ? "active" : ""}
              aria-current={activeSlide === 2 ? "true" : "false"}
              aria-label="Slide 3"
              style={{ width: "25%", marginTop: "-90px" }}
              onClick={() => handleClick(2)}
            ></button>
            <button
              type="button"
              data-bs-target="#carouselExampleCaptions"
              data-bs-slide-to="3"
              className={activeSlide === 3 ? "active" : ""}
              aria-current={activeSlide === 3 ? "true" : "false"}
              aria-label="Slide 4"
              style={{ width: "25%", marginTop: "-90px" }}
              onClick={() => handleClick(3)}
            ></button>
          </div>
          <div className="carousel-inner">
            <div
              className={`carousel-item ${activeSlide === 0 ? "active" : ""}`}
            >
              <h2 className="h2_text">
              Cryptocurrency just  got better
                <br />
              </h2>
              <h2 className="second_h2_text">Why Choose us?</h2>
              <p className="p_text">Select the right platform to confidently invest and trade in the exciting world of cryptocurrencies.</p>
              <button className="buttonStyle">
                
                kjbvjghghjlj
              </button>
              <button className="buttonStyle2" style={{ marginLeft: "0px" }}>
                vbkbnl,n
              </button>
            </div>
            <div
              className={`carousel-item ${activeSlide === 1 ? "active" : ""}`}
            >
              <h2 className="h2_text">              Cryptocurrency just  got better</h2>
              <h2 className="second_h2_text">trading bot</h2>
              <p className="p_text">Select the right platform to confidently invest and trade in the exciting world of cryptocurrencies.</p>
              <button className="buttonStyle2">fdjkihkj</button>
            </div>
            <div
              className={`carousel-item ${activeSlide === 2 ? "active" : ""}`}
            >
              <h2 className="h2_text">     Cryptocurrency just  got better</h2>
              <p className="p_text">Select the right platform to confidently invest and trade in the exciting world of cryptocurrencies.</p>
              <button className="buttonStyle2">n nmbjknj</button>
            </div>
            <div
              className={`carousel-item ${activeSlide === 3 ? "active" : ""}`}
            >
              <h2 className="h2_text">              Cryptocurrency just  got better
</h2>
              <p className="p_text">Select the right platform to confidently invest and trade in the exciting world of cryptocurrencies.</p>
              <button className="buttonStyle2">hbkhij;j</button>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

export default Carousel